name: test_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.5
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/